### ISSUE TITLE
Writing Test Down

### ISSUE THREAD

**Issue by Mr8ND** [Mr8ND/TC-prediction-bands#40]
@Mr8ND - this needs be done after lat/lon correction, and other debugging. Functions can't be correctly written before this (ie. Issue #33) must be done before this issue. ~ @benjaminleroy

The following needs to be done to include tests in the repository
- [x] 1. Understand where and how tests for R package should be written @Mr8ND 
- [x] 2.0. write list of functions that need tests @Mr8ND 
- [x] 2.1. Identify basic and mechanical functions to be included in the tests 
- [x] 3. Obtain a sample of 1/2 TCs to be used as "sanity-check" for the confidence band pipeline - all the 4 confidence bands should be obtained so that we can re-run the test anytime we change something about any of the 4
- [ ] 5. (Optional) Investigate whether TRAVIS integration might be quick and useful for a repository

**Comment by benjaminleroy** [comment]
stochastic nature of things like area of PB

**Comment by benjaminleroy** [comment]
Looks like Travis can be incorporated via https://github.com/r-lib/covr/blob/master/README.md

**Comment by benjaminleroy** [comment]
http://r-pkgs.had.co.nz/tests.html

**Comment by benjaminleroy** [comment]
finished
