### ISSUE TITLE
Main script cleanup (figures and analysis code)

### ISSUE THREAD

**Issue by RobinMDunn** [Mr8ND/TC-prediction-bands#42]
For scripts in the `main` folder:
- [x] 1. we should rename the files such that the order is obvious (following [Hadley Wickam's style guide](http://adv-r.had.co.nz/Style.html) ) in the following manner: @RobinMDunn (First pass done by @benjaminleroy)
    - [x] 1. @RobinMDunn: is `2-save_train_test.R` reproducible? Why is "new_data" just an empty list?

```{r}
0-download.R
1-parse.R
2-explore.R
```
- [x] 2. we should create a `README.md` for this directory that tells people how to run the files, e.g. @Mr8ND 

```{r}
Rscript main/credible_interval_pipeline.R a b
```

with detailed information on what parameters a, b should be. Additional comments about "parallelization" would also be useful. 

- [x] 3. When done with our analysis we should drop the "Sys.Date()" approach to make the pipeline **completely** reproducible @Mr8ND 

- [x] 4. Clean up Table and Images output: @RobinMDunn @benjaminleroy
    - [x] 4.a. Make all images and tables end up in `report/images/` and `report/tables` respectively. Note that tables can be created with `xtable` like done in `main/acc_vs_area_results.R`.
    - [x] 4.b. Push most recent code for creating tables.  (@benjaminleroy)
    - [x] 4.c. In tables, change Auto to AR and change Non-Auto to Non-AR.
    - [x] 4.d. make graphics and table use of CB types and Sim types consistent. Possibly follow approach in`main/acc_vs_area_results.R` (approx line `85`) - or that in `main/cb_validation_results.R` - they are different.
- [x] 4.5. Move a clean version of `latex` document into `report` folder. @RobinMDunn 
     - [x] 4.5.1. Clean up Latex (remove images that are not used, put sections in as `section` folder, etc) **on sharelatex**. @RobinMDunn 

Visualization functions:
- [x] write visualization functions to take in either the raw objection or the desired data frame (@benjaminleroy)

**Comment by benjaminleroy** [comment]
this belongs in code cleanup

**Comment by benjaminleroy** [comment]
Wow- Ben did everything
